Feature: Participant Setup

# Note that researcher chooses their own participant id. Unique code is generated by the app 
Scenario: Setup participant on server
    Given The researcher is logged in to the web interface
    When They select the "Add participant" option
    Then They will be able to enter participant details
    And The details shall include a participant id and a unique code
    And The researcher can click a button "Save"
    And The researcher will see a message to confirm that the account has been created

