Feature: Participant Setup

Scenario: Setup participant on server
    Given The researcher is logged in to the web interface
    When They select the "Add participant" option
    Then They will be able to enter a participant id of their choosing and a unique code (generated by the app)
    And The participant account will be created and stored in the database
    And The researcher will see a message to confirm that the account has been created

