Feature: Participant Setup

Story: Setup participant on server
    Scenario: Setup participant on server
        Given: The researcher is logged in to the web interface
        When: They select the "Add participant" option
        Then: They will be able to enter a participant id of their choosing and a unique code (generated by the app)
        And: The participant account will be created and stored in the database
        And: The researcher will see a message to confirm that the account has been created

Story: View participants
    Scenario: View participants 
        Given: The researcher has previously setup one or more participants
        When: The researcher logs in to the web interface
        Then: They will see a "summary view" of existing participants
        And: The view shall be ordered by participant id.
        And: For each participant the view shall (initially - we will add more later) include participant id and unique code
        
